# Generated by Django 6.0.5 on 2026-06-29 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(null=True)),
                ("message", models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=50, null=True)),
                ("number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "other_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("date_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(null=True)),
                ("password", models.CharField(max_length=20, null=True)),
                (
                    "profile_image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
